version: '3'
services:
  hdb-products:
    build: .
    container_name: hdb-products
    ports:
      - "8080:8080"
      - "8000:8000"
    environment:
      VCAP_SERVICES: >
        {
          "postgresql": [{"binding_name": null,"credentials": {"dbname": "postgres","hostname": "postgres","password": "pguser","port": "5432","uri": "postgres://pguser:pguser@postgres:5432/postgres","username": "pguser"},"label": "postgresql","name": "postgres","plan": null,"provider": null,"syslog_drain_url": null,"tags": ["postgresql", "relational"],"volume_mounts": []}],
          "hana": [
            {
              "binding_guid": "b8f95bbf-af93-472e-82a3-4fb98352d6a8",
              "binding_name": null,
              "credentials": {
                "certificate": "-----BEGIN CERTIFICATE-----\nMIIDrzCCApegAwIBAgIQCDvgVpBCRrGhdWrJWZHHSjANBgkqhkiG9w0BAQUFADBh\nMQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3\nd3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBD\nQTAeFw0wNjExMTAwMDAwMDBaFw0zMTExMTAwMDAwMDBaMGExCzAJBgNVBAYTAlVT\nMRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5j\nb20xIDAeBgNVBAMTF0RpZ2lDZXJ0IEdsb2JhbCBSb290IENBMIIBIjANBgkqhkiG\n9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4jvhEXLeqKTTo1eqUKKPC3eQyaKl7hLOllsB\nCSDMAZOnTjC3U/dDxGkAV53ijSLdhwZAAIEJzs4bg7/fzTtxRuLWZscFs3YnFo97\nnh6Vfe63SKMI2tavegw5BmV/Sl0fvBf4q77uKNd0f3p4mVmFaG5cIzJLv07A6Fpt\n43C/dxC//AH2hdmoRBBYMql1GNXRor5H4idq9Joz+EkIYIvUX7Q6hL+hqkpMfT7P\nT19sdl6gSzeRntwi5m3OFBqOasv+zbMUZBfHWymeMr/y7vrTC0LUq7dBMtoM1O/4\ngdW7jVg/tRvoSSiicNoxBN33shbyTApOB6jtSj1etX+jkMOvJwIDAQABo2MwYTAO\nBgNVHQ8BAf8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUA95QNVbR\nTLtm8KPiGxvDl7I90VUwHwYDVR0jBBgwFoAUA95QNVbRTLtm8KPiGxvDl7I90VUw\nDQYJKoZIhvcNAQEFBQADggEBAMucN6pIExIK+t1EnE9SsPTfrgT1eXkIoyQY/Esr\nhMAtudXH/vTBH1jLuG2cenTnmCmrEbXjcKChzUyImZOMkXDiqw8cvpOp/2PV5Adg\n06O/nVsJ8dWO41P0jmP6P6fbtGbfYmbW0W5BjfIttep3Sp+dWOIrWcBAI+0tKIJF\nPnlUkiaY4IBIqDfv8NZ5YBberOgOzW6sRBc4L0na4UU+Krk2U886UAb3LujEV0ls\nYSEY1QSteDwsOoBrp+uvFRTp2InBuThs4pFsiv9kuXclVzDAGySj4dzp30d8tbQk\nCAUw7C29C79Fv1C5qfPrmAESrciIxpg0X40KPMbp1ZWVbd4=\n-----END CERTIFICATE-----",
                "driver": "com.sap.db.jdbc.Driver",
                "hdi_password": "Jo38GD5arvFwD2icvpiF.PJl-qfol7U9GbWzw5Zjao-rAdyllfh6.bj4-eoOFZskKNCe_yRqlmmE-AM5-bzkHhksSWxjCqGRgJ-Y_vtE5hhbUKEr0.fInaNWFlNvLX.8",
                "hdi_user": "HDB_HDI_DB_1_0ATHLJZD47EOJFFUMUUM9FFH0_DT",
                "host": "0354e69a-2061-45e6-bfed-00a1225a8cfc.hana.trial-us10.hanacloud.ondemand.com",
                "password": "Gy5_oLzPZgnrruFBql9Ogh5oXeWkJ8EBu5cCfRr2Fn0y_ZqOhNJxWfl_V-G9C2kZo2G9wbdO7aP7GcHxpwI-oOSd2lR.8C8yN5lKUpRJYx3IweIAE._2RsgvrQmMLCLG",
                "port": "443",
                "schema": "HDB_HDI_DB_1",
                "url": "jdbc:sap://0354e69a-2061-45e6-bfed-00a1225a8cfc.hana.trial-us10.hanacloud.ondemand.com:443?encrypt=true&validateCertificate=true&currentschema=HDB_HDI_DB_1",
                "user": "HDB_HDI_DB_1_0ATHLJZD47EOJFFUMUUM9FFH0_RT"
              },
              "instance_guid": "2014938a-494b-4b0c-800b-ad41f68bcf18",
              "instance_name": "hdb-hdidb-ws-hlt22",
              "label": "hana",
              "name": "hdb-hdidb-ws-hlt22",
              "plan": "hdi-shared",
              "provider": null,
              "syslog_drain_url": null,
              "tags": [
                "hana",
                "database",
                "relational"
              ],
              "volume_mounts": []
            }]
        }
      VCAP_APPLICATION: >
        {
          "cf_api":"https://api.cf.eu10.hana.ondemand.com"
        }
      SPRING_PROFILES_ACTIVE: dev, cloud

    depends_on:
      - postgres

  postgres:
    hostname: postgres
    container_name: postgres
    build: .docker/db/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pguser
      - POSTGRES_DB=postgres
    restart: always
