version: '3'
services:
  hdb-admin:
    build: .
    container_name: hdb
    ports:
      - "8080:8080"
    environment:
      VCAP_SERVICES: >
        {
          "postgresql": [{"binding_name": null,"credentials": {"dbname": "postgres","hostname": "postgres","password": "pguser","port": "5432","uri": "postgres://pguser:pguser@postgres:5432/postgres","username": "pguser"},"label": "postgresql","name": "postgres","plan": null,"provider": null,"syslog_drain_url": null,"tags": ["postgresql", "relational"],"volume_mounts": []}]
        }
      VCAP_APPLICATION: >
        {
          "cf_api":"https://api.cf.eu10.hana.ondemand.com"
        }
      SPRING_PROFILES_ACTIVE: dev, cloud
      JBP_CONFIG_SPRING_AUTO_RECONFIGURATION: "{enabled: false}"
    depends_on:
      - postgres

  postgres:
    hostname: postgres
    container_name: postgres
    build: .docker/db/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pguser
      - POSTGRES_DB=postgres
    restart: always
